/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaoDien;

import duLieu.MonAn;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import giaoDien.FDangNhap;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hung
 */
public class pn_ThongTinMonAn extends javax.swing.JPanel {

    /**
     * Creates new form pn_ThongTinMonAn
     */
    MonAn thongTinMonAn = new MonAn();
    boolean chonMon;

    public boolean isChonMon() {
        return chonMon;
    }

    public void setChonMon(boolean chonMon) {
        this.chonMon = chonMon;
    }

    public pn_ThongTinMonAn() {
        initComponents();

    }

    public MonAn getThongTinMonAn() {
        return thongTinMonAn;
    }

    public void setThongTinMonAn(MonAn thongTinMonAn) {
        this.thongTinMonAn = thongTinMonAn;
    }

    public void showthongtin() {
//        pn_ThongTinMonAn.WIDTH=100;
txt_Gia_ThongTinMonAn.setBackground(new Color(0,0,0,0));
        txt_MaMon_ThongTinMonAn.setText(thongTinMonAn.getMaMon());
        txt_TenMon_ThongTinMonAn.setText(thongTinMonAn.getTenMon());
        txt_Gia_ThongTinMonAn.setText(Integer.toString(thongTinMonAn.getGiaTien()));
        XuLyHinhAnh xla = new XuLyHinhAnh();
        Image img = new Image() {
            @Override
            public int getWidth(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getHeight(ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public ImageProducer getSource() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Graphics getGraphics() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getProperty(String name, ImageObserver observer) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        };
        try {
            img = xla.createImageFromByteArray(thongTinMonAn.getImg(), "jpg");
//            img =xla.resize(img, lb_img_ThongTinMonAn.getWidth(), lb_img_ThongTinMonAn.getHeight());
        } catch (IOException ex) {
            Logger.getLogger(FDangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
//        ImageIcon icon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lb_img_ThongTinMonAn.getWidth(), lb_img_ThongTinMonAn.getHeight(), Image.SCALE_SMOOTH));

        ImageIcon icon = new ImageIcon(img);
        lb_img_ThongTinMonAn.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_img_ThongTinMonAn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_MaMon_ThongTinMonAn = new javax.swing.JTextField();
        txt_TenMon_ThongTinMonAn = new javax.swing.JTextField();
        txt_Gia_ThongTinMonAn = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(280, 240));
        setMinimumSize(new java.awt.Dimension(280, 240));
        setPreferredSize(new java.awt.Dimension(280, 240));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("MÃ MÓN");

        jLabel2.setText("TÊN MÓN");

        lb_img_ThongTinMonAn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("GIÁ");

        txt_MaMon_ThongTinMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaMon_ThongTinMonAnActionPerformed(evt);
            }
        });
        txt_MaMon_ThongTinMonAn.setText(thongTinMonAn.getMaMon());

        txt_TenMon_ThongTinMonAn.setText(thongTinMonAn.getTenMon());

        txt_Gia_ThongTinMonAn.setText(String.valueOf(thongTinMonAn.getGiaTien()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(lb_img_ThongTinMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_TenMon_ThongTinMonAn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txt_MaMon_ThongTinMonAn, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Gia_ThongTinMonAn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MaMon_ThongTinMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_TenMon_ThongTinMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_img_ThongTinMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Gia_ThongTinMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MaMon_ThongTinMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaMon_ThongTinMonAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaMon_ThongTinMonAnActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        System.out.println("giaoDien.pn_ThongTinMonAn.dgtttttttttttttttttformMouseClicked()");
        if (this.chonMon == true) {
            Border border = null;
//        .setBackground(new Color(255, 255, 255, 150));
            this.setBorder(border);

            this.chonMon = false;
        } else {
            Border border = BorderFactory.createBevelBorder(0, Color.yellow, Color.YELLOW);
//        .setBackground(new Color(255, 255, 255, 150));
            this.setBorder(border);
            this.chonMon = true;
        }

//     
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_img_ThongTinMonAn;
    private javax.swing.JTextField txt_Gia_ThongTinMonAn;
    private javax.swing.JTextField txt_MaMon_ThongTinMonAn;
    private javax.swing.JTextField txt_TenMon_ThongTinMonAn;
    // End of variables declaration//GEN-END:variables
}
